FROM node

WORKDIR /build/server
COPY server/package.json /build/server
RUN npm i
COPY ./server /build/server

ARG SERVER_PORT
ARG ME_CONFIG_MONGODB_SERVER
ARG ME_CONFIG_MONGODB_ADMINUSERNAME
ARG ME_CONFIG_MONGODB_ADMINPASSWORD
ARG ME_CONFIG_MONGODB_URL

EXPOSE 3001

CMD ["npm", "run", "dev"]